name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: AdityaNair07
          outputs: dist/snake.svg
        env:
          ACTIONS_RUNNER_DEBUG: true

      - name: Push Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
